### ISSUE TITLE
Issues when building dockerfile

### ISSUE THREAD

**Issue by zichunxx** [mazpie/redundancy-action-spaces#1]
Hi! @mazpie 

Thanks for your generous sharing! I'm very interested in your work and want to reproduce the simulation training process.

I'm new to docker. Please forgive me if I raise some easy issues.

1. During the build process, I found `wget http://www.coppeliarobotics.com/files/CoppeliaSim_Edu_V4_1_0_Ubuntu20_04.tar.xz && \` will trigger the `404 not found` error. I think the right link should be `https://www.coppeliarobotics.com/files/V4_1_0/CoppeliaSim_Edu_V4_1_0_Ubuntu20_04.tar.xz`.

2. For the following part 
```
# install VS Code (code-server)
RUN curl -fsSL https://code-server.dev/install.sh | sh
RUN code-server --install-extension ms-python.python ms-toolsai.jupyter
```
, the `code-server` command cannot be found. Here is the error report:

```

0.349 /bin/sh: 1: code-server: not found
------
Dockerfile:96
--------------------
  94 |     # install VS Code (code-server)
  95 |     RUN curl -fsSL https://code-server.dev/install.sh | sh
  96 | >>> RUN code-server --install-extension ms-python.python ms-toolsai.jupyter
  97 |     
  98 |     # install VS Code extensions
--------------------
ERROR: failed to solve: process "/bin/sh -c code-server --install-extension ms-python.python ms-toolsai.jupyter" did not complete successfully: exit code: 127
"docker run" requires at least 1 argument.
See 'docker run --help'.

Usage:  docker run [OPTIONS] IMAGE [COMMAND] [ARG...]

Create and run a new container from an image
```

Thanks for checking this issue!

**Comment by mazpie** [comment]
Hi @zichunxx,

thanks for pointing out the issues. 

1. they might have updated the URL in the CoppeliaSim recently. I think the URL you posted should work fine
2. you can comment out the whole part about VS Code and VS Code extensions, as it's not essential for the code to work (I think I will remove it in a future commit to ensure easier reproducibility)

Let me know if you encounter any other problems

**Comment by zichunxx** [comment]
Thanks for your reply. I think you have provided clear instructions about deploying the Docker image. I just know less about Docker and CoppeliaSim.

One more question before diving into the training process: how did you debug the program with the settings in `xvfb-run.sh` and `vscode`? I googled this question but found less about this requirement. Would you mind giving some tips about `launch.json`? 

Sincerely.

**Comment by mazpie** [comment]
Debugging programs with `xvfb` can be tricky indeed.

I can recommend using `debugpy` or `debugpy-run` (you can find it [here](https://pypi.org/project/debugpy-run/))

This allows you to start the process with xvfb and attach the VSCode debugger to the process while it's running.

If the problems with the Dockerfile are resolved, I will close the issue

**Comment by zichunxx** [comment]
You are so nice. Thanks for your help. I have no questions about Dockerfile currently.
